@token = a041b92755d93425495bcdbf139cf58292cdae010f8c153c81a3413b8d840b06

### Verbo GET – listar todos
GET http://localhost:8000/produto/ HTTP/1.1
Authorization: Bearer {{token}}

### Verbo GET – listar todos
curl -X 'GET' 'http://localhost:8000/produto/' \
    -H 'accept: application/json' \
    -H 'Authorization: Bearer {{token}}'

### ao logar, gera um token que deve ser usado para acessar as rotas da API
curl -X 'POST' 'http://127.0.0.1:8000/token' \
    -H 'accept: application/json' \
    -H 'Content-Type: application/x-www-form-urlencoded' \
    -d 'username=abc&password=bolinhas'

### token gerado
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmMiLCJleHAiOjE3NDg5MjMzNzF9.L7gOexC8FBtMlEjKtNrbAGtprEQvh-AzKjXg5Yi_vaY

### teste token
curl -X 'GET' 'http://127.0.0.1:8000/token/logado/' \
    -H 'accept: application/json' \
    -H 'Authorization: Bearer {{token}}'

### Verbo GET – listar um
GET http://localhost:8000/produto/10 HTTP/1.1
Authorization: Bearer {{token}}

### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome": "Tarcisio Correa",
    "descricao": "123",
    "foto": "1",
    "valor_unitario": 10
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/2 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nome": "Tarcisio Correa",
    "descricao": "123",
    "foto": "1",
    "valor_unitario": 10
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/3 HTTP/1.1
Authorization: Bearer {{token}}